### ISSUE TITLE
Debt: upstream changes from vscode-node-sqlite3

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-node-sqlite3#11]
- [x] CodeQL changes https://github.com/microsoft/vscode-node-sqlite3/commit/7112bf834ad0e9b0d247a0374f9cfe9666bde330 @deepak1556 - https://github.com/TryGhost/node-sqlite3/pull/1614
 - [x] Type fixes https://github.com/microsoft/vscode-node-sqlite3/commit/2a6d60a6707c3712135c23b8e3c6eeabfcdb8225 @bpasero - https://github.com/mapbox/node-sqlite3/pull/1527
 - [x] Disable non-throwable exceptions https://github.com/microsoft/vscode-node-sqlite3/commit/85456ab12e22ff971cd12279ec0a8993bd637a7b @deepak1556 - https://github.com/TryGhost/node-sqlite3/pull/1615
 - [x] Extend Sqlite3 error codes https://github.com/microsoft/vscode-node-sqlite3/commit/59a82b27af26664474acf0fc1ea7fb9698a7df31 @bpasero - https://github.com/mapbox/node-sqlite3/pull/1528

**Comment by daniellockyer** [comment]
Hey @bpasero and @deepak1556 🙂 I'm one of the new maintainers for `node-sqlite3` after Ghost [took over stewardship](https://github.com/TryGhost/node-sqlite3/issues/1292#issuecomment-1095337163) of the project.

I wanted to let you know that we're absolutely open to upstreaming your changes. I'm currently working on getting CI fixed up and getting a new release w/ prebuilt binaries but then we should be good to see what can be done.

Note: Ghost actually uses `@vscode/sqlite3` after Knex switched to your fork 😛 I'm hopeful we can switch back to the original version 🙂

**Comment by kibertoad** [comment]
We will switch after new release of sqlite is available :)

**Comment by bpasero** [comment]
@daniellockyer that is excellent news! we would love to switch then back to the official version ❤️

**Comment by daniellockyer** [comment]
`sqlite3` v5.0.3 has been released 🙂

**Comment by daniellockyer** [comment]
Hey @bpasero - I've fixed up the repo and it's feeling more stable now. Would you like to rebase your PRs and then we can get them merged 🙂

**Comment by bpasero** [comment]
Yes will do in our debt week (early June).

**Comment by bpasero** [comment]
Done, will see for the other two.

**Comment by bpasero** [comment]
We plan to drop our fork, but we have currently no available engineering resources to do it. It is not as simple as just changing the library, it is also validating all the changes that went in (including SQLite itself) brings no regressions.

**Comment by daniellockyer** [comment]
That's understandable 🙂 Let me know if I can help anywhere
