### ISSUE TITLE
RETURNING support

### ISSUE THREAD

**Issue by kibertoad** [microsoft/vscode-node-sqlite3#15]
underlying sqlite3 version does support RETURNING at last, but when we try to execute INSERT query with RETURNING clause in them, we get `undefined` response. Is there something that needs to be done to make that work?

**Comment by bpasero** [comment]
Our intent is not to create another distribution of this library but track the original library as closely as possible. In fact, https://github.com/microsoft/vscode-node-sqlite3/issues/11 tracks upstreaming our changes and then we will delete this repository very likely.
