### ISSUE TITLE
Binaries are missing

### ISSUE THREAD

**Issue by tkalliom** [microsoft/vscode-node-sqlite3#16]
It seems that the binary distribution has not been set up at all. The `binary` section of `package.json` still refers to the Mapbox S3 bucket, which obviously does not have binaries for the newer versions.

**Comment by gpetrov** [comment]
Yes and please add Linux Arm as well Darwin Arm64 binaries. It was so often requested with the original map box sqlite3 module and it breaks so many docker deploys because of the missing binaries.

**Comment by bpasero** [comment]
Our intent is not to create another distribution of this library but track the original library as closely as possible. In fact, https://github.com/microsoft/vscode-node-sqlite3/issues/11 tracks upstreaming our changes and then we will delete this repository very likely.
