### ISSUE TITLE
ERROR in ./node_modules/@vscode/sqlite3/build/Release/vscode-sqlite3.node

### ISSUE THREAD

**Issue by JunsikLee** [microsoft/vscode-node-sqlite3#36]
### Issue Summary

Developing vscode extension.
Execution error after adding library.
Please help me with the solution.

package.json
```
    "devDependencies": {
        "@faker-js/faker": "^7.6.0",
        "@types/glob": "^8.0.0",
        "@types/mocha": "^10.0.0",
        "@types/node": "16.x",
        "@types/vscode": "^1.73.0",
        "@typescript-eslint/eslint-plugin": "^5.42.0",
        "@typescript-eslint/parser": "^5.42.0",
        "@vscode/test-electron": "^2.2.0",
        "eslint": "^8.26.0",
        "glob": "^8.0.3",
        "mocha": "^10.1.0",
        "ts-loader": "^9.4.1",
        "typescript": "^4.8.4",
        "webpack": "^5.74.0",
        "webpack-cli": "^4.10.0"
    },
    "dependencies": {
        "@types/lodash": "^4.14.191",
        "@vscode/sqlite3": "^5.1.3-vscode",
        "lodash": "^4.17.21"
    }
```

### Relevant logs or output

ERROR in ./node_modules/@vscode/sqlite3/build/Release/vscode-sqlite3.node 1:2
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/@vscode/sqlite3/lib/sqlite3-binding.js 4:16-63
 @ ./node_modules/@vscode/sqlite3/lib/sqlite3.js 2:16-47
 @ ./src/main/api/handle/EventViewHandle.ts 6:15-41
 @ ./src/main/api/ApiProcess.ts 5:26-61
 @ ./src/main/api/ApiService.ts 4:21-44
 @ ./src/main/webview/pages/WebViewPageScheduleTraceGraph.ts 5:21-52
 @ ./src/main/webview/WebViewManager.ts 4:40-88
 @ ./src/main/init.ts 8:25-60
 @ ./src/extension.ts 7:13-35

webpack 5.75.0 compiled with 1 error in 936 ms
    [webpack-cli] Compiler is watching files for updates...

### Version

@vscode/sqlite3": "^5.1.3-vscode"

### Node.js Version

v18.15.0

### How did you install the library?

windows10, 64bit, intel

**Comment by bpasero** [comment]
We have a great extension developer community over on [GitHub discussions](https://github.com/microsoft/vscode-discussions/discussions) and [Slack](https://aka.ms/vscode-dev-community) where extension authors help each other. This is a great place for you to ask questions and find support.

Happy Coding!

**Comment by JunsikLee** [comment]
Thank you 😀 Have a good time!!
